ai_provider_amazeeio.settings:
  type: config_object
  label: 'amazee.ai AI Settings'
  mapping:
    api_key:
      type: string
      label: 'The API key for amazee.ai AI to be loaded via Key module'
    moderation:
      type: boolean
      label: 'Enable moderation requests before each request.'
    amazee_host:
      type: string
      label: 'The host to use for Amazee AI API calls.'
    host:
      type: string
      label: 'The host to use for LLM API calls.'
    postgres_host:
      type: string
      label: 'The host to use for the Postgres database.'
    postgres_port:
      type: integer
      label: 'The port to use for the Postgres database.'
    postgres_default_database:
      type: string
      label: 'The database to use for the Postgres database.'
    postgres_username:
      type: string
      label: 'The user to use for the Postgres database.'
    postgres_password:
      type: string
      label: 'The password to use for the Postgres database to be loaded via Key module.'
    redirect_on_login:
      type: boolean
      label: 'If enabled, redirect the admin user on login to the provider settings page if not configured.'
