drupical.settings:
  type: config_object
  label: 'Events Feed Settings'
  constraints:
    FullyValidatable: ~
  mapping:
    max_age:
      type: integer
      label: 'Cache events for max-age seconds.'
      constraints:
        Range:
          min: 0
    cron_interval:
      type: integer
      label: 'Cron interval for fetching events in seconds.'
      constraints:
        Range:
          min: 0
    limit:
      type: integer
      label: 'Number of events that will be displayed.'
      constraints:
        Range:
          min: 0
